COUNTRY_CODES = ['AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR',
       'EL', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'NL', 'NO', 'PL', 'PT',
       'RO', 'SI', 'SK', 'SE', 'UK']

COUNTRY_NUMERICAL_CODES_MAP = {
    'AT': 1,
    'BE': 2,
    'BG': 3,
    'CH': 4,
    'CY': 5,
    'CZ': 6,
    'DE': 7,
    'DK': 8,
    'EE': 9,
    'ES': 10,
    'FI': 11,
    'FR': 12,
    'EL': 13,
    'HR': 14,
    'HU': 15,
    'IE': 16,
    'IT': 17,
    'LT': 18,
    'LU': 19,
    'LV': 20,
    'NL': 21,
    'NO': 22,
    'PL': 23,
    'PT': 24,
    'RO': 25,
    'SI': 26,
    'SK': 27,
    'SE': 28,
    'UK': 29
}